export const SITE = {
  author: "Marko",
  title: "Markopteryx",
  website: "https://markopteryx.dev/",
  profile: "https://markopteryx.dev/",
  desc: "A personal blog about programming, technology, and life.",
  ogImage: "site-og.jpg",
  lightAndDarkMode: true,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Australia/Sydney",
} as const;
